services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
    -  "3306:3306"
    volumes:
    - willimeter:/var/lib/mysql

volumes:
  willimeter: