spring:
  datasource:
    url: jdbc:mysql://localhost:3306/willimeter?createDatabaseIfNotExist=true
    username: root
    password: admin
    show-sql: true

  jpa:
    hibernate:
      ddl-auto: update


